Allow alternative timestamp field time formats in the database
flipstone/orville pull request #166
Opened 2021-08-09 16:30 UTC by OwenGraves

This solution is kind of ugly, and there might be a better way to go about this (be happy to discuss), but this allows for parsing a few more representations in a timestamp field in the database (such as not having the milliseconds specified).

2021-08-09 16:53 UTC, qxjit commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/SqlValue.hs
> +    <|> parseTime "%F %T"      unTxt
I was imagining that we would actually have a new `SqlType` to cover `timestamp without time zone`. Is that something you'd be willing to tackle rather than having this one parsing function try to handle both?

2021-08-09 20:14 UTC, qxjit requested changes
The new `SqlType` and `FieldDefinition` should have at least the equivalent tests to those on the existing timestamp field.

2021-08-09 20:14 UTC, qxjit commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/SqlType.hs
> +    , sqlTypeId = LibPQ.Oid 1184
I assume that `timestamp without time zone` has a different OID

2021-08-09 20:14 UTC, qxjit commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/SqlValue.hs
> +    toUTCWithoutZoneTime,
Ugh.. naming these is hard. I think they should start with `toUTCTime` since they are creating a `UTCTime` value. Maybe `toUTCTimeWithZone` and `toUTCTimeWithoutZone`?

2021-08-09 20:21 UTC, OwenGraves commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/SqlType.hs
> +    , sqlTypeId = LibPQ.Oid 1184
Yeah I was wondering about that, where do you look up OIDs?

2021-08-09 22:03 UTC, telser commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/SqlType.hs
> +    , sqlTypeId = LibPQ.Oid 1184
The easiest place is in postgres itself. A really rough query you can run is 
```sql
select typname, oid, pg_catalog.obj_description(oid) from pg_catalog.pg_type ;
```

Which should give you the name, the oid, and a description, but this isn't filtering out internal types or anything so the list is big (376 rows when I run it against the orville db container)

2021-08-10 13:53 UTC, qxjit approved these changes
:heart:

2021-08-10 14:44 UTC, closed without merging