LibPQ: Add `distinct`
flipstone/orville pull request #167
Opened 2021-08-09 18:22 UTC by mitchellvitez

Adds `selectClause` and `selectExpr` under `queryExpr` to support `SELECT DISTINCT ...`. Doesn't support multiple-column `DISTINCT`s yet.

I'm a little unsure about the niceness of just passing a `Bool` to `selectExpr`. Can add a newtype wrapper to make it more clear what that flag means if wanted

2021-08-09 22:09 UTC, telser commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/Expr/Select/SelectExpr.hs
> +selectExpr :: Bool -> SelectExpr
I think you're right that a Bool feels sub-optimal at best. I think we should definitely explore something here, a newtype, or an ADT, whatever works best.

2021-08-10 13:54 UTC, qxjit commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/Expr/Select/SelectExpr.hs
> +selectExpr :: Bool -> SelectExpr
Agree, Even a single constructor type `data Distinct = Distinct` would let us then write `Maybe Distinct -> Select Expr` here.

2021-08-10 14:06 UTC, mitchellvitez commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/Expr/Select/SelectExpr.hs
> +selectExpr :: Bool -> SelectExpr
the grammar (see https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#set-quantifier) implies an ADT `data SetQuantifier = Distinct | All`, with `All` as a default. I do like having it be a `Maybe` with `Nothing` implying `All`, so we don't have to use the name `SetQuantifier` and the default feels more default

2021-08-17 12:37 UTC, qxjit requested changes

2021-08-17 12:37 UTC, qxjit commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/TableDefinition.hs
> +  Maybe Expr.SelectClause ->
It seems like this function always required an `Expr.SelectClause`, rather than leaving the user to wonder what happens if you don't specify one. Either than, or it should take a `Maybe Distinct`.

2021-08-17 12:37 UTC, qxjit commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/TableDefinition.hs
> +        fromMaybe (Expr.selectClause . Expr.selectExpr $ Just Expr.Distinct) mbSelectClause
I wouldn't expect `DISTINCT` to be the default here when `Nothing` is passed (but see my comment above about not allowing `Nothing` anyway)

2021-08-19 14:50 UTC, qxjit approved these changes

2021-08-19 15:09 UTC, merged