Adds modules to query 'pg_catalog'
flipstone/orville pull request #190
Opened 2021-09-15 15:38 UTC by qxjit

This adds modules for several 'pg_catalog' tables and a higher-level
'DatabaseDescription' for describing a number of tables at once using
'Plan'.

I had to augment 'Expr' an 'Plan' a bit to support new types, including
the ability to query using tuples. Although the 'Expr' module supports
any size tuple, it does not enforce that the caller using same-sized
tuples when building the queries.

In the higher order 'WhereCondition' and 'Operation' modules, I limited
the support to 2-tuples to easily enforce this without making the types
too crazy for the time being. We will want to iterate on this prior to
release.

For now, I stopped short of exposing any of this in 'Plan' directly.
Instead you currently have to reach down to 'Operation' to get the tuple
support.

2021-09-16 20:21 UTC, ysangkok requested changes
Grammar and spelling in comments 🧑‍🏫

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Plan/Operation.hs
> +    -- match only those rows that any (not all!) of the input parameters.
I expected a verb in final the subordinate clause. "That any of the input parameters" ... that the parameters what? That any of them do?

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Plan/Operation.hs
> +    -- suitable to be returned as an explanation of
I think "as" is confusing here because it is unclear to me whether it is a role being played or an explanation. I suggest "because" ?

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Plan/Operation.hs
> +    -- 'executeOneWhereCondition' would when given a list of parameters. For
executeManyWhereCondition on line 180 would "return". But here, what would executeOneWhereCondition do? There is no verb after "would". Is the intention to say that an explanation can be returned? But in comment block on executeManyWhereCondition, there are two occurances of "return". Why is there only one here?

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Plan/Operation.hs
> +  with function such as 'findOne' and 'findAll' to construct an 'Operation'.
with *a* function?

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Plan/Operation.hs
> +  with function such as 'findOne' and 'findAll' to construct an 'Operation'.
with *a* function?

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/test/Test/PgCatalog.hs
> +  Property.singletonNamedDBProperty "Can query the pg_attlibute table to find out about a column" $ \pool -> do
att*l*ibute should be attribute

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/Expr/Where/BooleanExpr.hs
> +  Checks that a the tuple constructed from the given columns in one of the
"a the"

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/Expr/Where/BooleanExpr.hs
> +  Checks that a the tuple constructed from the given columns in NOT one of the
"a the". And "in NOT" should probably be "is NOT"

2021-09-16 20:21 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/SqlValue.hs
> +  Attempts to decode a 'SqlValue' a Haskell 'Word' value. If decoding fails
suspected missing preposition "to" or "as" before "a"

2021-09-16 21:11 UTC, telser commented on orville-postgresql-libpq/test/Test/SqlType.hs
> +    ( String.fromString "Testing the decode of SMALLINT with value -2147483648"
The value here is off

2021-09-16 21:11 UTC, telser commented on orville-postgresql-libpq/test/Test/SqlType.hs
> +    ( String.fromString "Testing the decode of SMALLINT with value 2147483647"
Value off

2021-09-16 21:27 UTC, telser commented on orville-postgresql-libpq/src/Orville/PostgreSQL/PgCatalog/PgClass.hs
> +-}
Maybe it would be nice to include either here or on the to/from text functions a link to https://www.postgresql.org/docs/9.6/catalog-pg-class.html so future selves can find it?

2021-09-17 12:32 UTC, qxjit commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Plan/Operation.hs
> +    -- suitable to be returned as an explanation of
I'll reword this. "because" doesn't make any sense here to me. The where condition referenced is literally "the explanation" -- i.e. the where clause that would be shown when doing asking for an explanation of a plan.

2021-09-17 19:32 UTC, telser approved these changes

2021-09-17 19:34 UTC, merged