Adds AutoMigration of column types
flipstone/orville pull request #193
Opened 2021-09-20 16:44 UTC by qxjit

This uses the `pg_attribute` information from `pg_catalog` to determine
whether the type of a column needs to altered, or nullability added or
removed.

I also revised `SqlType` a bit to match the way information is actually
used during migrations, including _NOT_ needing the length of integer
types to know whether they need to be migrate (the OID is sufficient).

2021-09-20 17:10 UTC, ysangkok requested changes
comment nits

2021-09-20 17:10 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/PgCatalog/PgAttribute.hs
> +  -- and typemod when it is a domain type.
unclear precedence of and/or here

2021-09-20 17:10 UTC, ysangkok commented on orville-postgresql-libpq/test/Test/AutoMigration.hs
> +          -- the are pseoud-types in postgresql, rather than real column types.
pseudo

2021-09-20 17:10 UTC, ysangkok commented on orville-postgresql-libpq/test/Test/AutoMigration.hs
> +          -- an unable-to-cast error when attempting to migrate between them an
s/an$/and/

2021-09-21 14:59 UTC, telser commented on orville-postgresql-libpq/src/Orville/PostgreSQL/AutoMigration.hs
> +                  guard typeIsChanged
I think this would be easier to follow with an `if` instead of the `guard`. But then I pretty much always prefer explicit branching in some form over the more hidden imperative forms.

2021-09-21 17:30 UTC, qxjit commented on orville-postgresql-libpq/src/Orville/PostgreSQL/AutoMigration.hs
> +                  guard typeIsChanged
@telser I originally wrote both of these as an `if`, but thought it was too noisy. TBH, what I really wanted to do use `when`, but to do so collecting the migration steps would be a side effect in a write-like monad. I actually think that might be clearer overall because it would say something like

```
do
  when typeIsChanged (migrate $ alterColumnType...)
  when nullabilityIsChanged (migrate $ alterColumnNullability...)
```

I stopped short of actually adding a monad context to do that in, however. We can discuss further if we think it's worth it as we add more migration options.

2021-09-21 17:52 UTC, ysangkok approved these changes
looking good, thanks

2021-09-21 18:23 UTC, telser commented on orville-postgresql-libpq/src/Orville/PostgreSQL/AutoMigration.hs
> +                  guard typeIsChanged
I have an alternate proposal for that, but it can be discussed later when we get more migration options.

2021-09-21 18:58 UTC, telser approved these changes

2021-09-21 19:55 UTC, merged