Adds OrderBy as a nicer layer over OrderByExpr for SelectOptions
flipstone/orville pull request #196
Opened 2021-09-23 13:26 UTC by qxjit

This adds an `OrderBy` wrapper around `OrderByExpr`, similar to how
`WhereCondition` wraps `BooleanExpr`. Helper functions for building
`OrderBy` based on column names and field definitions are providing,
eliminating the need for the user to build the `OrderByExpr` directly.
Escape hatch functions are also provided for users that need more direct
access to the `Expr` layer.

2021-09-24 16:02 UTC, ysangkok requested changes
couple of comment typos ;)

2021-09-24 16:02 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/SelectOptions/OrderBy.hs
> +  included in it. You can use 'orderByToClause instead if you need the
unmatched quote

2021-09-24 16:02 UTC, ysangkok commented on orville-postgresql-libpq/src/Orville/PostgreSQL/Internal/SelectOptions/OrderBy.hs
> +  order expression witht the @ORDER BY@ clause included.
"witht"

2021-09-28 13:48 UTC, telser approved these changes

2021-09-28 13:54 UTC, merged