Removes extra parens in `conflictTargetForIndexExpr`
flipstone/orville pull request #393
Opened 2024-11-26 17:05 UTC by jlavelle

The `IndexBodyExpr` passed to `conflictTargetForIndexExpr` will already be parenthesized, and it is invalid PostgreSQL syntax to wrap it in an extra set of parens.

2024-11-26 17:06 UTC, onslaughtq approved these changes

2024-11-26 17:06 UTC, gera-cameron approved these changes
~(looks (good (too (me))))~
looks good to me

2024-11-26 17:44 UTC, telser requested changes

2024-11-26 17:44 UTC, telser commented on orville-postgresql/src/Orville/PostgreSQL/Expr/OnConflict.hs
> -    parensBody = RawSql.parenthesized $ RawSql.toRawSql idxBody
This is unfortunate. I see the helpers that are wrapping it in parens, but I don't think we can know for sure that _any_ `IndexBodyExpr` passed here will be wrapped that way (i.e. using the `SqlExpression` construction directly). :( That said, I _think_ you would want to put parens for then `IndexBodyExpr` always, so the assumption here is probably fine, but we should state that assumption in the docs.

2024-11-27 14:54 UTC, telser approved these changes

2024-11-27 15:00 UTC, merged